[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
yeve = "9Egc382nPtM559Zq4ucp3FSH1nhiPRqdpr5Zodnnsoko"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/mnt/d/Other/key/solana-key/my-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test.validator]
url = "https://api.mainnet-beta.solana.com"

[[test.validator.clone]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"